exp:
  a.a:
    İnterfaz Açıklama

  a.b:
    Profaz Başı Açıklama

  a.c:
    Profaz Sonu Açıklama

  a.d:
    Metafaz Açıklama

  a.e:
    Anafaz Açıklama

  a.f:
    Telofaz ve Sitokinez Açıklama

  b.a:
    "1"

quiztime: 600