exp:
  a.a:
    İnterfaz Açıklama

  a.b:
    Profaz Başı Açıklama

  a.c:
    Profaz Sonu Açıklama

  a.d:
    Metafaz Açıklama

  a.e:
    Anafaz Açıklama

  a.f:
    Telofaz ve Sitokinez Açıklama

  b.a:
    "1"
  b.b:
    "2"
  b.c:
    "3"
  b.d:
    "4"
  b.e:
    "5"
  b.f:
    "6"
  b.g:
    "7"
  b.h:
    "8"
  b.i:
    "9"
  b.j:
    "10"
  b.k:
    "11"

quiztime: 600